### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ioudas210** [ITDSystems/alvex-datagrid#2]
I am new to maven. But i setup maven2 on a debian box. Got it installed. Downloaded the zip of your files. Extracted it and ran your maven command. I get this output.

root@debian:~/build/alvex-datagrid-master/alvex-datagrid-repo# mvn package -DskipTests=true
[INFO] Scanning for projects...
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/maven/alfresco-sdk-parent/1.1.1/alfresco-sdk-parent-1.1.1.pom
[WARNING] Unable to get resource 'org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1' from repository alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public): Error transferring file: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: CA key usage check failed: keyCertSign bit is not set
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/org/alfresco/maven/alfresco-sdk-parent/1.1.1/alfresco-sdk-parent-1.1.1.pom
[WARNING] Unable to get resource 'org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1' from repository alfresco-public-snapshots (https://artifacts.alfresco.com/nexus/content/groups/public-snapshots): Error transferring file: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: CA key usage check failed: keyCertSign bit is not set
Downloading: http://repo1.maven.org/maven2/org/alfresco/maven/alfresco-sdk-parent/1.1.1/alfresco-sdk-parent-1.1.1.pom
[INFO] Unable to find resource 'org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1' in repository central (http://repo1.maven.org/maven2)
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: com.alvexcore.demo:alvex-datagrid-repo:amp:1.0-SNAPSHOT

Reason: Cannot find parent: org.alfresco.maven:alfresco-sdk-parent for project: com.alvexcore.demo:alvex-datagrid-repo:amp:1.0-SNAPSHOT for project com.alvexcore.demo:alvex-datagrid-repo:amp:1.0-SNAPSHOT

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Cannot find parent: org.alfresco.maven:alfresco-sdk-parent for project: com.alvexcore.demo:alvex-datagrid-repo:amp:1.0-SNAPSHOT for project com.alvexcore.demo:alvex-datagrid-repo:amp:1.0-SNAPSHOT
        at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:404)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:272)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:622)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.ProjectBuildingException: Cannot find parent: org.alfresco.maven:alfresco-sdk-parent for project: com.alvexcore.demo:alvex-datagrid-repo:amp:1.0-SNAPSHOT for project com.alvexcore.demo:alvex-datagrid-repo:amp:1.0-SNAPSHOT
        at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1396)
        at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:823)
        at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:508)
        at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:200)
        at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:604)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:487)
        at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:391)
        ... 12 more
Caused by: org.apache.maven.project.ProjectBuildingException: POM 'org.alfresco.maven:alfresco-sdk-parent' not found in repository: Unable to download the artifact from any repository

  org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public),
  alfresco-public-snapshots (https://artifacts.alfresco.com/nexus/content/groups/public-snapshots)

 for project org.alfresco.maven:alfresco-sdk-parent
        at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:605)
        at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1392)
        ... 18 more
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable to download the artifact from any repository

  org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public),
  alfresco-public-snapshots (https://artifacts.alfresco.com/nexus/content/groups/public-snapshots)

```
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:228)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:90)
    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:558)
    ... 19 more
```

Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to download the artifact from any repository
        at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:404)
        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:216)
        ... 21 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Fri Jan 02 16:26:55 EST 2015
[INFO] Final Memory: 4M/30M
[INFO] ------------------------------------------------------------------------

**Comment by ioudas210** [comment]
Using just maven on debian. I get

root@debian:~/build/alvex-datagrid/alvex-datagrid-repo#  mvn package -DskipTests=true
[INFO] Scanning for projects...
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/maven/alfresco-sdk-parent/1.1.1/alfresco-sdk-parent-1.1.1.pom
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/org/alfresco/maven/alfresco-sdk-parent/1.1.1/alfresco-sdk-parent-1.1.1.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.alvexcore.demo:alvex-datagrid-repo:1.0-SNAPSHOT (/root/build/alvex-datagrid/alvex-datagrid-repo/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1 from/to alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public): peer not authenticated and 'parent.relativePath' points at wrong local POM @ line 12, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by aviriel** [comment]
Looks like your maven cannot download some repositories because of security reasons. I have never seen such errors (I use Fedora), and it's better to ask such questions on Maven forums/StackOverflow.
